export const KEPEKLISTA1 = [
    {kep: "kepek/kep1.jpg",
     sorszam: 1},
    {kep: "kepek/kep2.jpg",
     sorszam: 2},
    {kep: "kepek/kep3.jpg",
     sorszam: 3},
    {kep: "kepek/kep4.jpg",
     sorszam: 4},
    {kep: "kepek/kep5.jpg",
     sorszam: 5},
    {kep: "kepek/kep6.jpg",
     sorszam: 6},
    {kep: "kepek/kep7.jpg",
     sorszam: 7},
    {kep: "kepek/kep8.jpg",
     sorszam: 8},
    {kep: "kepek/kep1.jpg",
     sorszam: 9},
    {kep: "kepek/kep2.jpg",
     sorszam: 10},
    {kep: "kepek/kep3.jpg",
     sorszam: 11},
    {kep: "kepek/kep4.jpg",
     sorszam: 12},
    {kep: "kepek/kep5.jpg",
     sorszam: 13},
    {kep: "kepek/kep6.jpg",
     sorszam: 14},
    {kep: "kepek/kep7.jpg",
     sorszam: 15},
    {kep: "kepek/kep8.jpg",
     sorszam: 16},
]

// export const KEPEKLISTA2 = [
//     {kep: "kepek/hatter.jpg",
//      sorszam: 1},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 2},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 3},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 4},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 5},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 6},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 7},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 8},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 9},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 10},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 11},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 12},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 13},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 14},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 15},
//     {kep: "kepek/hatter.jpg",
//      sorszam: 16},
// ]
